name = "queglims"
compatibility_date = "2025-09-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[deployments]]
format = "modules"
main = ".svelte-kit/cloudflare/_worker.js"