name = "your-project-name"
compatibility_date = "2025-09-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload = {
    format = "modules",
    dir = ".svelte-kit/cloudflare"
}

[assets]
directory = ".svelte-kit/cloudflare/client"